package persistent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect"
	entsql "entgo.io/ent/dialect/sql"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/minhhoccode111/go-clean-template-gin/internal/entity"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/sqlc"
	"github.com/minhhoccode111/go-clean-template-gin/pkg/postgres"
)

// TranslationRepo -.
// This layer acts as an Adapter between the database and business logic.
// It maps database-specific structures (generated by sqlc) to core business entities.
type TranslationRepo struct {
	*postgres.Postgres
	ent  *ent.Client
	sqlc *sqlc.Queries
}

// New -.
func New(pg *postgres.Postgres) *TranslationRepo {
	db := stdlib.OpenDBFromPool(pg.Pool)
	driver := entsql.OpenDB(dialect.Postgres, db)
	entClient := ent.NewClient(ent.Driver(driver))

	return &TranslationRepo{
		Postgres: pg,
		ent:      entClient,
		sqlc:     sqlc.New(pg.Pool),
	}
}

// GetHistoryWithEnt demonstrates CRUD-style reads with ent.
func (r *TranslationRepo) GetHistoryWithEnt(ctx context.Context) ([]entity.Translation, error) {
	rows, err := r.ent.History.Query().All(ctx)
	if err != nil {
		return nil, fmt.Errorf("TranslationRepo - GetHistoryWithEnt - r.ent.History.Query: %w", err)
	}

	entities := make([]entity.Translation, 0, len(rows))

	for _, row := range rows {
		entities = append(entities, entity.Translation{
			Source:      row.Source,
			Destination: row.Destination,
			Original:    row.Original,
			Translation: row.Translation,
		})
	}

	return entities, nil
}

// GetHistoryWithSqlc demonstrates query-style reads with sqlc.
func (r *TranslationRepo) GetHistoryWithSqlc(ctx context.Context) ([]entity.Translation, error) {
	rows, err := r.sqlc.GetHistory(ctx)
	if err != nil {
		return nil, fmt.Errorf("TranslationRepo - GetHistoryWithSqlc - r.sqlc.GetHistory: %w", err)
	}

	entities := make([]entity.Translation, 0, len(rows))

	for _, row := range rows {
		entities = append(entities, entity.Translation{
			Source:      row.Source,
			Destination: row.Destination,
			Original:    row.Original,
			Translation: row.Translation,
		})
	}

	return entities, nil
}

// StoreWithEnt demonstrates transactional writes with ent.
func (r *TranslationRepo) StoreWithEnt(ctx context.Context, t entity.Translation) error {
	tx, err := r.ent.Tx(ctx)
	if err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithEnt - r.ent.Tx: %w", err)
	}

	defer tx.Rollback() //nolint:errcheck // standard practice to ignore this

	_, err = tx.History.Create().
		SetSource(t.Source).
		SetDestination(t.Destination).
		SetOriginal(t.Original).
		SetTranslation(t.Translation).
		Save(ctx)
	if err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithEnt - tx.History.Create: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithEnt - tx.Commit: %w", err)
	}

	return nil
}

// StoreWithSqlc demonstrates transactional writes with sqlc.
func (r *TranslationRepo) StoreWithSqlc(ctx context.Context, t entity.Translation) error {
	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithSqlc - r.Pool.Begin: %w", err)
	}

	defer tx.Rollback(ctx) //nolint:errcheck // standard practice to ignore this

	queriesTx := r.sqlc.WithTx(tx)
	if err = queriesTx.Store(ctx, sqlc.StoreParams{
		Source:      t.Source,
		Destination: t.Destination,
		Original:    t.Original,
		Translation: t.Translation,
	}); err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithSqlc - queriesTx.Store: %w", err)
	}

	if err = tx.Commit(ctx); err != nil {
		return fmt.Errorf("TranslationRepo - StoreWithSqlc - tx.Commit: %w", err)
	}

	return nil
}
