package persistent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect"
	entsql "entgo.io/ent/dialect/sql"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/minhhoccode111/go-clean-template-gin/internal/entity"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/history"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/sqlc"
	"github.com/minhhoccode111/go-clean-template-gin/pkg/postgres"
)

// TranslationRepo -.
// This layer acts as an Adapter between the database and business logic.
// It maps database-specific structures (generated by sqlc) to core business entities.
type TranslationRepo struct {
	*postgres.Postgres
	ent  *ent.Client
	sqlc *sqlc.Queries
}

// New -.
func New(pg *postgres.Postgres) (*TranslationRepo, error) {
	db := stdlib.OpenDBFromPool(pg.Pool)
	entClient := ent.NewClient(ent.Driver(entsql.OpenDB(dialect.Postgres, db)))

	return &TranslationRepo{
		Postgres: pg,
		ent:      entClient,
		sqlc:     sqlc.New(pg.Pool),
	}, nil
}

// GetHistory -.
func (r *TranslationRepo) GetHistory(ctx context.Context) ([]entity.Translation, error) {
	rows, err := r.ent.History.Query().Order(history.ByID()).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("TranslationRepo - GetHistory - ent.Query: %w", err)
	}

	entities := make([]entity.Translation, 0, len(rows))

	for _, row := range rows {
		entities = append(entities, entity.Translation{
			Source:      row.Source,
			Destination: row.Destination,
			Original:    row.Original,
			Translation: row.Translation,
		})
	}

	return entities, nil
}

// Store -.
func (r *TranslationRepo) Store(ctx context.Context, t entity.Translation) error {
	_, err := r.ent.History.Create().
		SetSource(t.Source).
		SetDestination(t.Destination).
		SetOriginal(t.Original).
		SetTranslation(t.Translation).
		Save(ctx)
	if err != nil {
		return fmt.Errorf("TranslationRepo - Store - ent.Create: %w", err)
	}

	return nil
}
