package persistent

import (
	"context"
	"fmt"

	"github.com/minhhoccode111/go-clean-template-gin/internal/entity"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/sqlc"
	"github.com/minhhoccode111/go-clean-template-gin/pkg/postgres"
)

const _defaultEntityCap = 64

// TranslationRepo -.
// This layer acts as an Adapter between the database and business logic.
// It maps database-specific structures (generated by sqlc) to core business entities.
type TranslationRepo struct {
	*postgres.Postgres
	queries *sqlc.Queries
}

// New -.
func New(pg *postgres.Postgres) *TranslationRepo {
	return &TranslationRepo{
		Postgres: pg,
		queries:  sqlc.New(pg.Pool),
	}
}

// GetHistory -.
func (r *TranslationRepo) GetHistory(ctx context.Context) ([]entity.Translation, error) {
	rows, err := r.queries.GetHistory(ctx)
	if err != nil {
		return nil, fmt.Errorf("TranslationRepo - GetHistory - r.queries.GetHistory: %w", err)
	}

	entities := make([]entity.Translation, 0, len(rows))

	for _, row := range rows {
		entities = append(entities, entity.Translation{
			Source:      row.Source,
			Destination: row.Destination,
			Original:    row.Original,
			Translation: row.Translation,
		})
	}

	return entities, nil
}

// Store -.
func (r *TranslationRepo) Store(ctx context.Context, t entity.Translation) error {
	err := r.queries.Store(ctx, sqlc.StoreParams{
		Source:      t.Source,
		Destination: t.Destination,
		Original:    t.Original,
		Translation: t.Translation,
	})
	if err != nil {
		return fmt.Errorf("TranslationRepo - Store - r.queries.Store: %w", err)
	}

	return nil
}
