// Code generated by ent, DO NOT EDIT.

package history

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the history type in the database.
	Label = "history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldOriginal holds the string denoting the original field in the database.
	FieldOriginal = "original"
	// FieldTranslation holds the string denoting the translation field in the database.
	FieldTranslation = "translation"
	// Table holds the table name of the history in the database.
	Table = "history"
)

// Columns holds all SQL columns for history fields.
var Columns = []string{
	FieldID,
	FieldSource,
	FieldDestination,
	FieldOriginal,
	FieldTranslation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	DestinationValidator func(string) error
	// OriginalValidator is a validator for the "original" field. It is called by the builders before save.
	OriginalValidator func(string) error
	// TranslationValidator is a validator for the "translation" field. It is called by the builders before save.
	TranslationValidator func(string) error
)

// OrderOption defines the ordering options for the History queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByDestination orders the results by the destination field.
func ByDestination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestination, opts...).ToFunc()
}

// ByOriginal orders the results by the original field.
func ByOriginal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginal, opts...).ToFunc()
}

// ByTranslation orders the results by the translation field.
func ByTranslation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslation, opts...).ToFunc()
}
