// Code generated by ent, DO NOT EDIT.

package history

import (
	"entgo.io/ent/dialect/sql"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.History {
	return predicate.History(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.History {
	return predicate.History(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldID, id))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldSource, v))
}

// Destination applies equality check predicate on the "destination" field. It's identical to DestinationEQ.
func Destination(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDestination, v))
}

// Original applies equality check predicate on the "original" field. It's identical to OriginalEQ.
func Original(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldOriginal, v))
}

// Translation applies equality check predicate on the "translation" field. It's identical to TranslationEQ.
func Translation(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTranslation, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldSource, v))
}

// DestinationEQ applies the EQ predicate on the "destination" field.
func DestinationEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDestination, v))
}

// DestinationNEQ applies the NEQ predicate on the "destination" field.
func DestinationNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldDestination, v))
}

// DestinationIn applies the In predicate on the "destination" field.
func DestinationIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldDestination, vs...))
}

// DestinationNotIn applies the NotIn predicate on the "destination" field.
func DestinationNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldDestination, vs...))
}

// DestinationGT applies the GT predicate on the "destination" field.
func DestinationGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldDestination, v))
}

// DestinationGTE applies the GTE predicate on the "destination" field.
func DestinationGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldDestination, v))
}

// DestinationLT applies the LT predicate on the "destination" field.
func DestinationLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldDestination, v))
}

// DestinationLTE applies the LTE predicate on the "destination" field.
func DestinationLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldDestination, v))
}

// DestinationContains applies the Contains predicate on the "destination" field.
func DestinationContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldDestination, v))
}

// DestinationHasPrefix applies the HasPrefix predicate on the "destination" field.
func DestinationHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldDestination, v))
}

// DestinationHasSuffix applies the HasSuffix predicate on the "destination" field.
func DestinationHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldDestination, v))
}

// DestinationEqualFold applies the EqualFold predicate on the "destination" field.
func DestinationEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldDestination, v))
}

// DestinationContainsFold applies the ContainsFold predicate on the "destination" field.
func DestinationContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldDestination, v))
}

// OriginalEQ applies the EQ predicate on the "original" field.
func OriginalEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldOriginal, v))
}

// OriginalNEQ applies the NEQ predicate on the "original" field.
func OriginalNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldOriginal, v))
}

// OriginalIn applies the In predicate on the "original" field.
func OriginalIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldOriginal, vs...))
}

// OriginalNotIn applies the NotIn predicate on the "original" field.
func OriginalNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldOriginal, vs...))
}

// OriginalGT applies the GT predicate on the "original" field.
func OriginalGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldOriginal, v))
}

// OriginalGTE applies the GTE predicate on the "original" field.
func OriginalGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldOriginal, v))
}

// OriginalLT applies the LT predicate on the "original" field.
func OriginalLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldOriginal, v))
}

// OriginalLTE applies the LTE predicate on the "original" field.
func OriginalLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldOriginal, v))
}

// OriginalContains applies the Contains predicate on the "original" field.
func OriginalContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldOriginal, v))
}

// OriginalHasPrefix applies the HasPrefix predicate on the "original" field.
func OriginalHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldOriginal, v))
}

// OriginalHasSuffix applies the HasSuffix predicate on the "original" field.
func OriginalHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldOriginal, v))
}

// OriginalEqualFold applies the EqualFold predicate on the "original" field.
func OriginalEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldOriginal, v))
}

// OriginalContainsFold applies the ContainsFold predicate on the "original" field.
func OriginalContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldOriginal, v))
}

// TranslationEQ applies the EQ predicate on the "translation" field.
func TranslationEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTranslation, v))
}

// TranslationNEQ applies the NEQ predicate on the "translation" field.
func TranslationNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldTranslation, v))
}

// TranslationIn applies the In predicate on the "translation" field.
func TranslationIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldTranslation, vs...))
}

// TranslationNotIn applies the NotIn predicate on the "translation" field.
func TranslationNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldTranslation, vs...))
}

// TranslationGT applies the GT predicate on the "translation" field.
func TranslationGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldTranslation, v))
}

// TranslationGTE applies the GTE predicate on the "translation" field.
func TranslationGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldTranslation, v))
}

// TranslationLT applies the LT predicate on the "translation" field.
func TranslationLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldTranslation, v))
}

// TranslationLTE applies the LTE predicate on the "translation" field.
func TranslationLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldTranslation, v))
}

// TranslationContains applies the Contains predicate on the "translation" field.
func TranslationContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldTranslation, v))
}

// TranslationHasPrefix applies the HasPrefix predicate on the "translation" field.
func TranslationHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldTranslation, v))
}

// TranslationHasSuffix applies the HasSuffix predicate on the "translation" field.
func TranslationHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldTranslation, v))
}

// TranslationEqualFold applies the EqualFold predicate on the "translation" field.
func TranslationEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldTranslation, v))
}

// TranslationContainsFold applies the ContainsFold predicate on the "translation" field.
func TranslationContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldTranslation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.History) predicate.History {
	return predicate.History(sql.NotPredicates(p))
}
