-- Create "histories" table
CREATE TABLE "histories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "source" character varying NOT NULL,
  "destination" character varying NOT NULL,
  "original" character varying NOT NULL,
  "translation" character varying NOT NULL,
  PRIMARY KEY ("id")
);
