// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/history"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/predicate"
)

// HistoryUpdate is the builder for updating History entities.
type HistoryUpdate struct {
	config
	hooks    []Hook
	mutation *HistoryMutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (_u *HistoryUpdate) Where(ps ...predicate.History) *HistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *HistoryUpdate) SetSource(v string) *HistoryUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableSource(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *HistoryUpdate) SetDestination(v string) *HistoryUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableDestination(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetOriginal sets the "original" field.
func (_u *HistoryUpdate) SetOriginal(v string) *HistoryUpdate {
	_u.mutation.SetOriginal(v)
	return _u
}

// SetNillableOriginal sets the "original" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableOriginal(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetOriginal(*v)
	}
	return _u
}

// SetTranslation sets the "translation" field.
func (_u *HistoryUpdate) SetTranslation(v string) *HistoryUpdate {
	_u.mutation.SetTranslation(v)
	return _u
}

// SetNillableTranslation sets the "translation" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableTranslation(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetTranslation(*v)
	}
	return _u
}

// Mutation returns the HistoryMutation object of the builder.
func (_u *HistoryUpdate) Mutation() *HistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HistoryUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := history.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "History.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := history.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "History.destination": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Original(); ok {
		if err := history.OriginalValidator(v); err != nil {
			return &ValidationError{Name: "original", err: fmt.Errorf(`ent: validator failed for field "History.original": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Translation(); ok {
		if err := history.TranslationValidator(v); err != nil {
			return &ValidationError{Name: "translation", err: fmt.Errorf(`ent: validator failed for field "History.translation": %w`, err)}
		}
	}
	return nil
}

func (_u *HistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(history.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(history.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.Original(); ok {
		_spec.SetField(history.FieldOriginal, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translation(); ok {
		_spec.SetField(history.FieldTranslation, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HistoryUpdateOne is the builder for updating a single History entity.
type HistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HistoryMutation
}

// SetSource sets the "source" field.
func (_u *HistoryUpdateOne) SetSource(v string) *HistoryUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableSource(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *HistoryUpdateOne) SetDestination(v string) *HistoryUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableDestination(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetOriginal sets the "original" field.
func (_u *HistoryUpdateOne) SetOriginal(v string) *HistoryUpdateOne {
	_u.mutation.SetOriginal(v)
	return _u
}

// SetNillableOriginal sets the "original" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableOriginal(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetOriginal(*v)
	}
	return _u
}

// SetTranslation sets the "translation" field.
func (_u *HistoryUpdateOne) SetTranslation(v string) *HistoryUpdateOne {
	_u.mutation.SetTranslation(v)
	return _u
}

// SetNillableTranslation sets the "translation" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableTranslation(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetTranslation(*v)
	}
	return _u
}

// Mutation returns the HistoryMutation object of the builder.
func (_u *HistoryUpdateOne) Mutation() *HistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (_u *HistoryUpdateOne) Where(ps ...predicate.History) *HistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HistoryUpdateOne) Select(field string, fields ...string) *HistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated History entity.
func (_u *HistoryUpdateOne) Save(ctx context.Context) (*History, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryUpdateOne) SaveX(ctx context.Context) *History {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := history.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "History.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := history.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "History.destination": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Original(); ok {
		if err := history.OriginalValidator(v); err != nil {
			return &ValidationError{Name: "original", err: fmt.Errorf(`ent: validator failed for field "History.original": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Translation(); ok {
		if err := history.TranslationValidator(v); err != nil {
			return &ValidationError{Name: "translation", err: fmt.Errorf(`ent: validator failed for field "History.translation": %w`, err)}
		}
	}
	return nil
}

func (_u *HistoryUpdateOne) sqlSave(ctx context.Context) (_node *History, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "History.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, history.FieldID)
		for _, f := range fields {
			if !history.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != history.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(history.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(history.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.Original(); ok {
		_spec.SetField(history.FieldOriginal, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translation(); ok {
		_spec.SetField(history.FieldTranslation, field.TypeString, value)
	}
	_node = &History{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
