// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/history"
)

// HistoryCreate is the builder for creating a History entity.
type HistoryCreate struct {
	config
	mutation *HistoryMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *HistoryCreate) SetSource(v string) *HistoryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetDestination sets the "destination" field.
func (_c *HistoryCreate) SetDestination(v string) *HistoryCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetOriginal sets the "original" field.
func (_c *HistoryCreate) SetOriginal(v string) *HistoryCreate {
	_c.mutation.SetOriginal(v)
	return _c
}

// SetTranslation sets the "translation" field.
func (_c *HistoryCreate) SetTranslation(v string) *HistoryCreate {
	_c.mutation.SetTranslation(v)
	return _c
}

// Mutation returns the HistoryMutation object of the builder.
func (_c *HistoryCreate) Mutation() *HistoryMutation {
	return _c.mutation
}

// Save creates the History in the database.
func (_c *HistoryCreate) Save(ctx context.Context) (*History, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HistoryCreate) SaveX(ctx context.Context) *History {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HistoryCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "History.source"`)}
	}
	if _, ok := _c.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required field "History.destination"`)}
	}
	if _, ok := _c.mutation.Original(); !ok {
		return &ValidationError{Name: "original", err: errors.New(`ent: missing required field "History.original"`)}
	}
	if _, ok := _c.mutation.Translation(); !ok {
		return &ValidationError{Name: "translation", err: errors.New(`ent: missing required field "History.translation"`)}
	}
	return nil
}

func (_c *HistoryCreate) sqlSave(ctx context.Context) (*History, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HistoryCreate) createSpec() (*History, *sqlgraph.CreateSpec) {
	var (
		_node = &History{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(history.Table, sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(history.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(history.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.Original(); ok {
		_spec.SetField(history.FieldOriginal, field.TypeString, value)
		_node.Original = value
	}
	if value, ok := _c.mutation.Translation(); ok {
		_spec.SetField(history.FieldTranslation, field.TypeString, value)
		_node.Translation = value
	}
	return _node, _spec
}

// HistoryCreateBulk is the builder for creating many History entities in bulk.
type HistoryCreateBulk struct {
	config
	err      error
	builders []*HistoryCreate
}

// Save creates the History entities in the database.
func (_c *HistoryCreateBulk) Save(ctx context.Context) ([]*History, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*History, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HistoryCreateBulk) SaveX(ctx context.Context) []*History {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
