// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/history"
	"github.com/minhhoccode111/go-clean-template-gin/internal/repo/persistent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescSource is the schema descriptor for source field.
	historyDescSource := historyFields[0].Descriptor()
	// history.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	history.SourceValidator = historyDescSource.Validators[0].(func(string) error)
	// historyDescDestination is the schema descriptor for destination field.
	historyDescDestination := historyFields[1].Descriptor()
	// history.DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	history.DestinationValidator = historyDescDestination.Validators[0].(func(string) error)
	// historyDescOriginal is the schema descriptor for original field.
	historyDescOriginal := historyFields[2].Descriptor()
	// history.OriginalValidator is a validator for the "original" field. It is called by the builders before save.
	history.OriginalValidator = historyDescOriginal.Validators[0].(func(string) error)
	// historyDescTranslation is the schema descriptor for translation field.
	historyDescTranslation := historyFields[3].Descriptor()
	// history.TranslationValidator is a validator for the "translation" field. It is called by the builders before save.
	history.TranslationValidator = historyDescTranslation.Validators[0].(func(string) error)
}
