// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HistoryColumns holds the columns for the "history" table.
	HistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeString},
		{Name: "destination", Type: field.TypeString},
		{Name: "original", Type: field.TypeString},
		{Name: "translation", Type: field.TypeString},
	}
	// HistoryTable holds the schema information for the "history" table.
	HistoryTable = &schema.Table{
		Name:       "history",
		Columns:    HistoryColumns,
		PrimaryKey: []*schema.Column{HistoryColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HistoryTable,
	}
)

func init() {
	HistoryTable.Annotation = &entsql.Annotation{
		Table: "history",
	}
}
