// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type History struct {
	ID          int64
	Source      string
	Destination string
	Original    string
	Translation string
}
