// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/minhhoccode111/go-clean-template-gin/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistoryWithEnt mocks base method.
func (m *MockTranslationRepo) GetHistoryWithEnt(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryWithEnt", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryWithEnt indicates an expected call of GetHistoryWithEnt.
func (mr *MockTranslationRepoMockRecorder) GetHistoryWithEnt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryWithEnt", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistoryWithEnt), arg0)
}

// GetHistoryWithSqlc mocks base method.
func (m *MockTranslationRepo) GetHistoryWithSqlc(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryWithSqlc", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryWithSqlc indicates an expected call of GetHistoryWithSqlc.
func (mr *MockTranslationRepoMockRecorder) GetHistoryWithSqlc(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryWithSqlc", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistoryWithSqlc), arg0)
}

// StoreWithEnt mocks base method.
func (m *MockTranslationRepo) StoreWithEnt(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWithEnt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWithEnt indicates an expected call of StoreWithEnt.
func (mr *MockTranslationRepoMockRecorder) StoreWithEnt(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWithEnt", reflect.TypeOf((*MockTranslationRepo)(nil).StoreWithEnt), arg0, arg1)
}

// StoreWithSqlc mocks base method.
func (m *MockTranslationRepo) StoreWithSqlc(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWithSqlc", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWithSqlc indicates an expected call of StoreWithSqlc.
func (mr *MockTranslationRepoMockRecorder) StoreWithSqlc(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWithSqlc", reflect.TypeOf((*MockTranslationRepo)(nil).StoreWithSqlc), arg0, arg1)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockTranslationCache is a mock of TranslationCache interface.
type MockTranslationCache struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationCacheMockRecorder
	isgomock struct{}
}

// MockTranslationCacheMockRecorder is the mock recorder for MockTranslationCache.
type MockTranslationCacheMockRecorder struct {
	mock *MockTranslationCache
}

// NewMockTranslationCache creates a new mock instance.
func NewMockTranslationCache(ctrl *gomock.Controller) *MockTranslationCache {
	mock := &MockTranslationCache{ctrl: ctrl}
	mock.recorder = &MockTranslationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationCache) EXPECT() *MockTranslationCacheMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationCache) GetHistory(ctx context.Context) ([]entity.Translation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationCacheMockRecorder) GetHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationCache)(nil).GetHistory), ctx)
}

// InvalidateHistory mocks base method.
func (m *MockTranslationCache) InvalidateHistory(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateHistory", ctx)
}

// InvalidateHistory indicates an expected call of InvalidateHistory.
func (mr *MockTranslationCacheMockRecorder) InvalidateHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateHistory", reflect.TypeOf((*MockTranslationCache)(nil).InvalidateHistory), ctx)
}

// SetHistory mocks base method.
func (m *MockTranslationCache) SetHistory(ctx context.Context, history []entity.Translation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", ctx, history)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockTranslationCacheMockRecorder) SetHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockTranslationCache)(nil).SetHistory), ctx, history)
}
